# Generated by Django 5.0.7 on 2024-07-24 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Goods', '0002_alter_banner_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=233)),
                ('region', models.TextField()),
                ('email', models.URLField(max_length=233)),
                ('facebook', models.URLField(max_length=233)),
                ('twitter', models.URLField(max_length=233)),
                ('linking', models.URLField(max_length=233)),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
